#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/../config/config.sh"

OUT="${RESULTS}/population_structure"
mkdir -p "$OUT"

# Population-structure analyses use the strict autosomal SNP dataset generated by
# 04_filter_variants.sh, followed by the LD-pruning procedure described in Methods.
INPUT_VCF="$STRICT_VCF"

if [[ ! -f "$INPUT_VCF" ]]; then
    echo "ERROR: strict structure input VCF not found: $INPUT_VCF" >&2
    echo "Run scripts/04_filter_variants.sh first." >&2
    exit 1
fi

# Convert the strict autosomal VCF to PLINK binary format.
plink \
  --vcf "$INPUT_VCF" \
  --double-id \
  --set-missing-var-ids @:# \
  --make-bed \
  --out "${OUT}/structure.full"

# Record the exact number of markers entering LD pruning.
wc -l < "${OUT}/structure.full.bim" > "${OUT}/markers_before_ld_pruning.txt"

# LD pruning: 50-marker window, 5-marker step, r2 threshold 0.2.
plink \
  --bfile "${OUT}/structure.full" \
  --indep-pairwise 50 5 0.2 \
  --out "${OUT}/structure"

plink \
  --bfile "${OUT}/structure.full" \
  --extract "${OUT}/structure.prune.in" \
  --make-bed \
  --out "${OUT}/structure.pruned"

wc -l < "${OUT}/structure.pruned.bim" > "${OUT}/markers_after_ld_pruning.txt"

printf 'Markers before LD pruning: '
cat "${OUT}/markers_before_ld_pruning.txt"
printf 'Markers after LD pruning: '
cat "${OUT}/markers_after_ld_pruning.txt"

# PCA of all 20 individuals.
plink \
  --bfile "${OUT}/structure.pruned" \
  --pca 20 \
  --out "${OUT}/PCA_all"

# Wild-only PCA using the SAME LD-pruned marker set, restricted to wild samples.
awk -F'\t' 'NR>1 && $2=="Wild" {print $1, $1}' "$SAMPLES_WGS" \
  > "${OUT}/wild.keep"

plink \
  --bfile "${OUT}/structure.pruned" \
  --keep "${OUT}/wild.keep" \
  --pca 20 \
  --out "${OUT}/PCA_wild"

# ADMIXTURE K=2-5, 10 independent runs per K.
# The original analysis used ADMIXTURE --cv without an explicit fold number and
# replicate numbers 1-10 as random seeds. Keep that behavior here.
echo -e "K\tReplicate\tCV_error" > "${OUT}/admixture_CV_all.tsv"

for K in 2 3 4 5; do
  mkdir -p "${OUT}/admixture/K${K}"

  for REP in $(seq 1 10); do
    run="${OUT}/admixture/K${K}/rep${REP}"
    mkdir -p "$run"

    cp "${OUT}/structure.pruned.bed" "$run/input.bed"
    cp "${OUT}/structure.pruned.bim" "$run/input.bim"
    cp "${OUT}/structure.pruned.fam" "$run/input.fam"

    (
      cd "$run"
      admixture \
        --cv \
        -j"${THREADS}" \
        -s "${REP}" \
        input.bed \
        "$K" \
        2>&1 | tee admixture.log
    )

    CV=$(grep "CV error" "$run/admixture.log" | \
      sed -E 's/.*CV error.*: ([0-9.eE+-]+).*/\1/')
    echo -e "${K}\t${REP}\t${CV}" >> "${OUT}/admixture_CV_all.tsv"
  done
done

# Summarize CV error and identify the minimum-CV replicate for each K.
python "$(dirname "$0")/summarize_admixture_cv.py" \
  --root "${OUT}/admixture" \
  --output "${OUT}/admixture_cv_summary.tsv"

# Select the minimum-CV replicate for each K and copy its Q/P files for plotting.
echo -e "K\tBest_replicate\tCV_error" > "${OUT}/admixture_best.tsv"
for K in 2 3 4 5; do
  best=$(awk -v K="$K" 'BEGIN{best=1e99; rep=""} NR>1 && $1==K {if($3<best){best=$3; rep=$2}} END{print rep"\t"best}' "${OUT}/admixture_cv_summary.tsv")
  rep=$(printf '%s' "$best" | cut -f1 | sed 's/^rep//')
  cv=$(printf '%s' "$best" | cut -f2)
  echo -e "${K}\t${rep}\t${cv}" >> "${OUT}/admixture_best.tsv"
  cp "${OUT}/admixture/K${K}/rep${rep}/input.${K}.Q" "${OUT}/best.K${K}.Q"
  cp "${OUT}/admixture/K${K}/rep${rep}/input.${K}.P" "${OUT}/best.K${K}.P"
done

# Mean CV error across the 10 independent runs for each K.
echo -e "K\tMean_CV_error" > "${OUT}/admixture_cv_mean.tsv"
for K in 2 3 4 5; do
  awk -v K="$K" 'NR>1 && $1==K {sum+=$3; n++} END{if(n>0) print K"\t"sum/n}' \
    "${OUT}/admixture_cv_summary.tsv" >> "${OUT}/admixture_cv_mean.tsv"
done
