suppressPackageStartupMessages(library(ggplot2))
a <- commandArgs(trailingOnly=TRUE); if(length(a)!=3) stop('Usage: Rscript 22_plot_figure2.R population_structure_dir wgs_samples.tsv outdir')
dir <- a[1]; meta <- read.delim(a[2]); out <- a[3]; dir.create(out,showWarnings=FALSE,recursive=TRUE)
ev <- read.table(file.path(dir,'PCA_all.eigenvec'),header=FALSE); ee <- scan(file.path(dir,'PCA_all.eigenval'),quiet=TRUE)
names(ev)[1:4] <- c('FID','sample_id','PC1','PC2'); ev <- merge(ev,meta[,c('sample_id','ecotype')],by='sample_id')
p <- ggplot(ev,aes(PC1,PC2,color=ecotype,label=sample_id))+geom_point(size=3)+theme_classic()+xlab(sprintf('PC1 (%.1f%%)',100*ee[1]/sum(ee)))+ylab(sprintf('PC2 (%.1f%%)',100*ee[2]/sum(ee)))
ggsave(file.path(out,'Figure2A_PCA.pdf'),p,width=6,height=5)
cv <- read.delim(file.path(dir,'admixture_cv_summary.tsv')); s <- aggregate(CV_error~K,cv,function(x)c(mean=mean(x),sd=sd(x))); sm <- data.frame(K=s$K,mean=s$CV_error[,1],sd=s$CV_error[,2])
p <- ggplot(sm,aes(K,mean))+geom_point()+geom_line()+geom_errorbar(aes(ymin=mean-sd,ymax=mean+sd),width=.1)+theme_classic()+ylab('Cross-validation error')
ggsave(file.path(out,'Figure2D_ADMIXTURE_CV.pdf'),p,width=5,height=4)
