suppressPackageStartupMessages({library(ggplot2); library(patchwork)})
a <- commandArgs(trailingOnly=TRUE); if(length(a)!=2) stop('Usage: Rscript 23_plot_figure3.R results_dir outdir')
r <- a[1]; out <- a[2]; dir.create(out,showWarnings=FALSE,recursive=TRUE)
ho <- read.delim(file.path(r,'diversity','observed_heterozygosity.tsv'))
pi <- read.delim(file.path(r,'diversity','pi','PI_5Mb_blocks.tsv')); ps <- read.delim(file.path(r,'diversity','pi','pi_block_bootstrap_summary.tsv'))
roh <- read.delim(file.path(r,'roh','roh_summary.tsv')); ld <- read.delim(file.path(r,'ld','LD_decay_0_30kb.tsv'))
p1 <- ggplot(ho,aes(ecotype,Ho,fill=ecotype))+geom_boxplot(outlier.shape=NA)+geom_jitter(width=.08)+stat_summary(fun=mean,geom='point',shape=23,fill='white',size=3)+theme_classic()+theme(legend.position='none')
pl <- rbind(data.frame(Group='Wild',Pi=pi$PI_Wild),data.frame(Group='Farm',Pi=pi$PI_Farm))
p2 <- ggplot(pl,aes(Group,Pi,fill=Group))+geom_boxplot(outlier.shape=NA)+stat_summary(fun=mean,geom='point',shape=23,fill='white',size=3)+theme_classic()+theme(legend.position='none')+labs(subtitle=sprintf('Delta pi=%.3g, 95%% CI %.3g to %.3g',ps$delta_wild_minus_farm,ps$ci_2.5,ps$ci_97.5))
p3 <- ggplot(roh,aes(ecotype,FROH,fill=ecotype))+geom_boxplot(outlier.shape=NA)+geom_jitter(width=.08)+stat_summary(fun=mean,geom='point',shape=23,fill='white',size=3)+theme_classic()+theme(legend.position='none')
p4 <- ggplot(ld,aes(Dist/1000,r2,color=Group))+geom_line()+theme_classic()+xlab('Distance (kb)')+ylab(expression(r^2))
ggsave(file.path(out,'Figure3.pdf'),(p1|p2)/(p3|p4),width=11,height=9)
